alias ollama-stop="~/ollama-k8s/stop.sh"
alias grafana-password="kubectl --namespace monitoring get secrets monitoring-grafana -o jsonpath=\"{.data.admin-password}\" | base64 -d ; echo"
alias grafana-pass="kubectl --namespace monitoring get secrets monitoring-grafana -o jsonpath=\"{.data.admin-password}\" | base64 -d ; echo"
alias grafana-password="kubectl --namespace monitoring get secrets monitoring-grafana -o jsonpath=\"{.data.admin-password}\" | base64 -d ; echo"
alias monitoring-start="kubectl scale deployment monitoring-grafana monitoring-kube-state-metrics opencost -n monitoring --replicas=1 && kubectl scale statefulset prometheus-monitoring-kube-prometheus-prometheus alertmanager-monitoring-kube-prometheus-alertmanager -n monitoring --replicas=1"
alias monitoring-stop="kubectl scale deployment monitoring-grafana monitoring-kube-state-metrics opencost -n monitoring --replicas=0 && kubectl scale statefulset prometheus-monitoring-kube-prometheus-prometheus alertmanager-monitoring-kube-prometheus-alertmanager -n monitoring --replicas=0"
export PATH="$HOME/.local/bin:$PATH"
alias ollama-start="~/mac-setup/scripts/start.sh"
alias ai-llama="lsof -ti:8080 | xargs kill -9 2>/dev/null; sleep 1; cd ~/llama-cpp-turboquant && ./build/bin/llama-server -m ~/models/llama33-70b-q4km.gguf --cache-type-k turbo3 --cache-type-v turbo3 -ngl 99 -c 32768 -fa on --host 0.0.0.0 --port 8080"
alias ai-qwen="lsof -ti:8080 | xargs kill -9 2>/dev/null; sleep 1; cd ~/llama-cpp-turboquant && ./build/bin/llama-server -m ~/models/qwen25-72b/qwen2.5-72b-instruct-q4_k_m-00001-of-00012.gguf --cache-type-k turbo3 --cache-type-v turbo3 -ngl 99 -c 32768 -fa on --host 0.0.0.0 --port 8080"
alias ai-mistral="lsof -ti:8080 | xargs kill -9 2>/dev/null; sleep 1; cd ~/llama-cpp-turboquant && ./build/bin/llama-server -m ~/models/mistral-7b-q4km.gguf --cache-type-k turbo3 --cache-type-v turbo3 -ngl 99 -c 32768 -fa on --host 0.0.0.0 --port 8080"
