ollama:
  image: ollama/ollama:0.18.3
  port: 11434
  resources:
    requests:
      memory: "6Gi"
      cpu: "1"
    limits:
      memory: "32Gi"
      cpu: "4"
  storage: 10Gi

openWebui:
  image: ghcr.io/open-webui/open-webui:v0.8.11
  port: 8080
  auth: "False"
  storage: 2Gi
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "500m"
