apiVersion: v1
kind: LimitRange
metadata:
  name: tenant-limits
  namespace: phoenix-dev
spec:
  limits:
    - type: Container
      default:           # Standard Limits wenn nichts angegeben
        cpu: 200m
        memory: 256Mi
      defaultRequest:    # Standard Requests wenn nichts angegeben
        cpu: 100m
        memory: 128Mi
      max:               # Maximale Werte pro Container
        cpu: "2"
        memory: 2Gi
      min:               # Minimale Werte pro Container
        cpu: 50m
        memory: 64Mi
---
apiVersion: v1
kind: LimitRange
metadata:
  name: tenant-limits
  namespace: atlas-dev
spec:
  limits:
    - type: Container
      default:
        cpu: 200m
        memory: 256Mi
      defaultRequest:
        cpu: 100m
        memory: 128Mi
      max:
        cpu: "1"
        memory: 1Gi
      min:
        cpu: 50m
        memory: 64Mi
