apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "mkcert-issuer"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - ollama.local
      secretName: ollama-cert-tls
  rules:
    - host: ollama.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-open-webui
                port:
                  number: {{ .Values.openWebui.port }}
