apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ollama
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Release.Name }}-ollama
  ports:
    - port: {{ .Values.ollama.port }}
      targetPort: {{ .Values.ollama.port }}
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-open-webui
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Release.Name }}-open-webui
  ports:
    - port: {{ .Values.openWebui.port }}
      targetPort: {{ .Values.openWebui.port }}
  type: ClusterIP
